apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 31001
  # secify a port as nodePort instead of choosing it at random
    nodePort: 31001
    # the port to be targeted by the nodePort and it is named as nodejs-port in Pod definition
    targetPort: nodejs-port
    protocol: TCP
  # label selector for selecting the Pod
  selector:
    app: helloworld
  type: NodePort
