apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-cache-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
      - name: redis-cache
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379