apiVersion: v1
kind: Service
metadata:
  name: redisapp-service
spec:
  ports:
  - port: 8181
    # specify a port as NodePort
    nodePort: 31001                          
    targetPort: redisapp-port
    protocol: TCP
  selector:
    app: redisapp
  type: NodePort
